apiVersion: v1
kind: ConfigMap
metadata:
  name: jobportal-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  # This should match the name of your DB Service
  DB_HOST: "jobportal-db-service" 
  DB_PORT: "3306"
  # URL for your frontend if needed for CORS
  FRONTEND_URL: "http://jobportal.com"
