name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Step 1: Build using the folder path (REMOVED the dot version)
      - run: docker build ./server -t soban11776/myfirstdeploy:latest
      
      # Step 2: Login
      - run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
      
      # Step 3: Push
      - run: docker push soban11776/myfirstdeploy:latest
